resolutions: [100000, 200000, 500000, 1000000]
labels: ["Control_B2", "Brd2_dep_rep1", "Brd2_dep_rep2"]
output: "/home/gridsan/aathreya/files/projects/brd2/main/results"
logpath: "/home/gridsan/aathreya/files/projects/brd2/main/results/logs"
root: "/home/gridsan/aathreya"
SRA_DATA_DIR: "/home/gridsan/aathreya/files/projects/brd2/data/SRA"
MM10_DATA: "/home/gridsan/aathreya/files/projects/brd2/data/mm10/"
DCHIC_DIR: "/home/gridsan/aathreya/pkgs/dcHiC/"